codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto

ignore:
  - "src/Annotation/**"
  - "src/Auth/**"
  - "src/Entity/**"
  - "src/Exception/**"
  - "src/Interceptor/**"
  - "src/Module/AppModule.php"
  - "src/Module/AuthModule.php"
  - "src/Module/DbModule.php"
  - "src/Module/PdoProvider.php"
  - "src/Module/QueryModule.php"
  - "src/Module/ServiceModule.php"
  - "src/Module/ValidationModule.php"
  - "src/Query/Impl/**"
  - "src/Query/CartItemQueryInterface.php"
  - "src/Query/CartQueryInterface.php"
  - "src/Query/CategoryQueryInterface.php"
  - "src/Query/ContactQueryInterface.php"
  - "src/Query/CouponQueryInterface.php"
  - "src/Query/CustomerAddressQueryInterface.php"
  - "src/Query/CustomerQueryInterface.php"
  - "src/Query/DeliveryQueryInterface.php"
  - "src/Query/FavoriteQueryInterface.php"
  - "src/Query/MailTemplateQueryInterface.php"
  - "src/Query/MasterQueryInterface.php"
  - "src/Query/MemberQueryInterface.php"
  - "src/Query/NewsQueryInterface.php"
  - "src/Query/OrderItemQueryInterface.php"
  - "src/Query/OrderQueryInterface.php"
  - "src/Query/OrderStatusHistoryQueryInterface.php"
  - "src/Query/PaymentQueryInterface.php"
  - "src/Query/PluginQueryInterface.php"
  - "src/Query/PointQueryInterface.php"
  - "src/Query/ProductCategoryQueryInterface.php"
  - "src/Query/ProductClassQueryInterface.php"
  - "src/Query/ProductImageQueryInterface.php"
  - "src/Query/ProductQueryInterface.php"
  - "src/Query/ReviewQueryInterface.php"
  - "src/Query/SearchQueryInterface.php"
  - "src/Query/ShippingQueryInterface.php"
  - "src/Query/TaxRuleQueryInterface.php"
  - "src/Query/WebhookQueryInterface.php"
  - "src/Resource/**"
  - "src/Service/**"
  - "src/Validation/**"

comment: false
